# Generated by Django 5.2.15 on 2026-08-14 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GajiTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(help_text='First day of the payroll month.')),
                ('hadir', models.CharField(blank=True, default='', max_length=32)),
                ('total_hadir', models.PositiveIntegerField(default=0)),
                ('hari_sakit', models.PositiveIntegerField(default=0)),
                ('hari_cuti', models.PositiveIntegerField(default=0)),
                ('hari_cuti_tambahan', models.PositiveIntegerField(default=0)),
                ('freq_pencapaian_target', models.PositiveIntegerField(default=0)),
                ('rate_target', models.PositiveIntegerField(default=0)),
                ('rate_non_target', models.PositiveIntegerField(default=0)),
                ('gaji_pokok', models.IntegerField(default=0)),
                ('rate_uang_makan', models.PositiveIntegerField(default=35000)),
                ('freq_lembur_6_jam', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rate_lembur_6_jam', models.PositiveIntegerField(default=0)),
                ('freq_hari_raya', models.PositiveIntegerField(default=0)),
                ('tunjangan_lama_kerja', models.PositiveIntegerField(default=0)),
                ('tunjangan_obat', models.PositiveIntegerField(default=0)),
                ('freq_alpa', models.PositiveIntegerField(default=0)),
                ('pot_bpjs_jht', models.IntegerField(default=0)),
                ('pot_bpjs_jp', models.IntegerField(default=0)),
                ('pot_bpjs_kesehatan', models.IntegerField(default=0)),
                ('pot_pph21', models.IntegerField(default=0)),
                ('pot_kehilangan', models.IntegerField(default=0)),
                ('koreksi_absensi', models.IntegerField(default=0)),
                ('total_gaji', models.PositiveIntegerField(default=0, help_text='Net.Transfer + Total Trf.U.Makan from the CSV.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gaji_temp', to='karyawan.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Gaji Temp',
                'ordering': ['-periode', 'karyawan__nama'],
                'constraints': [models.UniqueConstraint(fields=('karyawan', 'periode'), name='unique_gaji_temp_per_periode')],
            },
        ),
    ]
