# Generated by Django 5.2.8 on 2026-08-08 09:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karyawan_id', models.CharField(max_length=7, unique=True)),
                ('nama', models.CharField(max_length=128)),
                ('jabatan', models.CharField(blank=True, default='', max_length=128)),
                ('wilayah', models.CharField(blank=True, default='', max_length=3)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('must_change_password', models.BooleanField(default=True)),
                ('lokasi_kerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karyawan', to='core.lokasi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karyawan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Karyawan',
            },
        ),
    ]
