# Generated by Django 5.2.15 on 2026-08-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='cuti_tahunan',
            field=models.PositiveSmallIntegerField(default=12, help_text='Sisa jatah cuti tahunan (hari) yang masih bisa diambil.'),
        ),
    ]
