# Generated by Django 5.2.15 on 2026-08-14 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karyawan', '0001_initial'),
        ('lokasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_masuk', models.TimeField()),
                ('durasi', models.DurationField()),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='karyawan.karyawan')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='lokasi.lokasi')),
            ],
            options={
                'verbose_name_plural': 'Absensi',
                'ordering': ['-tanggal', 'karyawan__nama'],
            },
        ),
    ]
