# Generated by Django 5.2.8 on 2026-08-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0001_initial'),
        ('karyawan', '0001_initial'),
        ('lokasi', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='absensi',
            constraint=models.UniqueConstraint(fields=('karyawan', 'lokasi', 'tanggal', 'jam_masuk', 'durasi'), name='absensi_unique_exact_entry'),
        ),
    ]
