# Generated by Django 5.2.8 on 2026-09-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0002_absensi_unique_exact_entry'),
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the processed month.')),
                ('hari_hadir', models.PositiveIntegerField(default=0)),
                ('hari_telat', models.PositiveIntegerField(default=0)),
                ('hari_alpa', models.PositiveIntegerField(default=0)),
                ('hari_keluar_cepat', models.PositiveIntegerField(default=0)),
                ('total_menit_telat', models.PositiveIntegerField(default=0)),
                ('total_menit_lembur', models.PositiveIntegerField(default=0)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_absensi', to='karyawan.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Rekap Absensi',
                'ordering': ['-month', 'karyawan__nama'],
            },
        ),
        migrations.CreateModel(
            name='CatatanRekapAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('pesan', models.TextField()),
                ('rekap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='absensi.rekapabsensi')),
            ],
            options={
                'verbose_name_plural': 'Catatan Rekap Absensi',
                'ordering': ['tanggal', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rekapabsensi',
            constraint=models.UniqueConstraint(fields=('karyawan', 'month'), name='rekap_absensi_unique_karyawan_month'),
        ),
    ]
