# Generated by Django 5.2.8 on 2026-10-01 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0003_rekap_absensi'),
        ('cuti', '0002_pembatalan_statuses'),
        ('karyawan', '0001_initial'),
        ('lembur', '0001_initial'),
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('menit_telat', models.PositiveIntegerField(default=0)),
                ('cepat_keluar', models.PositiveIntegerField(default=0)),
                ('lembur', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('CUTI', 'Cuti'), ('ALPA', 'Alpa')], max_length=8)),
                ('absensi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kehadiran', to='absensi.absensi')),
                ('cuti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kehadiran', to='cuti.cuti')),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kehadiran', to='karyawan.karyawan')),
                ('permohonan_lembur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kehadiran', to='lembur.permohonanlembur')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kehadiran', to='shift.shift')),
            ],
            options={
                'verbose_name_plural': 'Kehadiran',
                'ordering': ['-tanggal', 'karyawan__nama', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('absensi__isnull', True)), fields=('karyawan', 'tanggal'), name='kehadiran_one_placeholder_per_day')],
            },
        ),
    ]
