# Generated by Django 5.2.8 on 2026-10-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0005_kehadiran_unique_day'),
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kehadiran', to='shift.shift'),
        ),
    ]
