# Generated by Django 5.2.15 on 2026-08-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Lokasi',
                'db_table': 'core_lokasi',
            },
        ),
    ]
