# Generated by Django 5.2.8 on 2026-08-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermohonanCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('IZIN_OFF', 'Izin Off'), ('IZIN_TELAT', 'Izin Telat'), ('IZIN_PULANG_CEPAT', 'Izin Pulang Cepat'), ('IZIN_LOKASI_BEDA', 'Izin Absen di Lokasi Beda'), ('CUTI_TAHUNAN', 'Cuti Tahunan'), ('CUTI_SAKIT', 'Cuti Sakit'), ('CUTI_DUKA_CITA', 'Cuti Duka Cita'), ('CUTI_MELAHIRKAN', 'Cuti Melahirkan'), ('CUTI_ISTRI_MELAHIRKAN', 'Cuti Istri Melahirkan'), ('CUTI_MENIKAH', 'Cuti Menikah'), ('CUTI_ANAK_MENIKAH', 'Cuti Anak Menikah'), ('CUTI_KHITANAN_ANAK', 'Cuti Khitanan Anak'), ('CUTI_PEMBAPTISAN_ANAK', 'Cuti Pembaptisan Anak')], max_length=32)),
                ('alasan', models.TextField(blank=True)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('MENUNGGU_SUPERVISOR', 'Menunggu Izin Supervisor'), ('MENUNGGU_HRD', 'Menunggu Izin HRD'), ('DITOLAK', 'Request Ditolak'), ('DIBATALKAN', 'Dibatalkan'), ('APPROVED', 'Approved')], default='MENUNGGU_SUPERVISOR', max_length=32)),
                ('hrd_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuti_diapprove_hrd', to='karyawan.karyawan')),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permohonan_cuti', to='karyawan.karyawan')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuti_disupervisi', to='karyawan.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Permohonan Cuti',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Cuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hari_cuti', to='cuti.permohonancuti')),
            ],
            options={
                'verbose_name_plural': 'Cuti',
                'ordering': ['-tanggal'],
            },
        ),
    ]
