# Generated by Django 5.2.8 on 2026-08-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('SENIN', 'Senin'), ('SELASA', 'Selasa'), ('RABU', 'Rabu'), ('KAMIS', 'Kamis'), ('JUMAT', 'Jumat'), ('SABTU', 'Sabtu'), ('MINGGU', 'Minggu')], max_length=8)),
                ('jam_masuk', models.TimeField()),
                ('jam_keluar', models.TimeField()),
                ('lokasi_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.lokasi')),
            ],
            options={
                'verbose_name_plural': 'Shift',
                'ordering': ['lokasi_kerja', 'hari', 'jam_masuk'],
            },
        ),
    ]
