# Generated by Django 5.2.15 on 2026-08-14 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermohonanLembur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alasan', models.TextField(blank=True)),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('MENUNGGU_SUPERVISOR', 'Menunggu Izin Supervisor'), ('MENUNGGU_HRD', 'Menunggu Izin HRD'), ('DITOLAK', 'Request Ditolak'), ('DIBATALKAN', 'Dibatalkan'), ('APPROVED', 'Approved')], default='MENUNGGU_SUPERVISOR', max_length=32)),
                ('hrd_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lembur_diapprove_hrd', to='karyawan.karyawan')),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permohonan_lembur', to='karyawan.karyawan')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lembur_disupervisi', to='karyawan.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Permohonan Lembur',
                'ordering': ['-tanggal'],
            },
        ),
    ]
