# Generated by Django 5.2.8 on 2026-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liburan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=64)),
                ('tanggal', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Liburan',
                'ordering': ['tanggal'],
            },
        ),
    ]
