# Generated by Django 5.2.8 on 2026-09-08 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuti', '0002_pembatalan_statuses'),
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langganan', to='karyawan.karyawan')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengikut', to='karyawan.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Langganan',
                'ordering': ['target__nama', 'target_id'],
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'target'), name='kalender_bersama_langganan_unique'), models.CheckConstraint(condition=models.Q(('subscriber', models.F('target')), _negated=True), name='kalender_bersama_langganan_not_self')],
            },
        ),
        migrations.CreateModel(
            name='NotifikasiDismiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalender_bersama_dismiss', to='cuti.permohonancuti')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_dismiss', to='karyawan.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Notifikasi Dismiss',
                'ordering': ['-dismissed_at'],
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'permohonan'), name='kalender_bersama_notifikasi_dismiss_unique')],
            },
        ),
    ]
